spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

rabbitmq:
  exchange:
    name: cart.exchange
  queue:
    name: cart.queue
  routing:
    key: cart.tracking


