spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    bus:
      enabled: true

#logging:
#  level:
##    trace to show log trace and debug
#    root: info
#    ca.lazanomentsoa.userservice: trace
#  file:
#    name: logs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7


server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: shutdown, bus-refresh
