spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    bus:
      enabled: true


server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: shutdown, bus-refresh
