spring:
  application:
    name: cart-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    bus:
      enabled: true

server:
  port: 8081

resilience4j:
  #rate limiter
  ratelimiter:
    instances:
      rateLimiterBreaker:
        timeout-duration: 0
        limit-refresh-period: 4s
        limit-for-period: 2

